### PR TITLE
upgrade account complete

### PR DESCRIPTION
**Pull request by Shimunta**
@cbeck

### CODE REVIEW

**Comment by cbeck** [comment]
👍

**Comment by cbeck** [comment]
You know I still can't merge these, right?

**Comment by Shimunta** [comment]
that is so strange, I added you as a collaborator after the first one

**Comment by Shimunta** [comment]
it says it is waiting for your response to accept collaboration

**Comment by cbeck** [comment]
Oh, ok. They changed their process. It used to be automatic, so I didn’t click the link. All good now.

**Pull request merged**
